metros = float(input("Uma distânica em metros: "))
print(f"A medida de {metros}m corresponde a")
print(f"{metros/ 1000}km")
print(f"{metros/100}hm")
print(f"{metros/10}dam")
print(f"{(metros*10):.0f}dm")
print(f"{(metros*100):.0f}cm")
print(f"{(metros*1000):.0f}mm")
