analisado = input("Digite algo: ")
print(f"O tipo primitivo desse valor é {type(analisado)}")
print(f"Só tem espaços? {str.isspace(analisado)}")
print(f"É um número? {str.isnumeric(analisado)}")
print(f"É alfabético? {str.isalpha(analisado)}")
print(f"É alfanumérico? {str.isalnum(analisado)}")
print(f"Está em maiúsculas? {str.isupper(analisado)}")
print(f"Está em minúsculas? {str.islower(analisado)}")
print(f"Está capitalizada? {str.istitle(analisado)}")
